on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v2.0.2
        with:
          force: true
      - name: Generate
        run: |
          repos=($(jq -cr '.repos.[].repo' meta.json))
          for i in "${!repos[@]}"; do
            curl ${repos[$i]} -o repo_$i.json
          done
          jq '[ $meta[].repos[].plugins[] as $plg | [.[][]] | .[].Tags+=$meta[].tags | map(select(.Name | . as $n | $plg | index($n)!=null)) ] | flatten' -s repo_*.json --slurpfile meta meta.json
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git add repo.json
          git diff --cached --quiet && exit 0
          git commit -m "Update repository"
          git push
